<a href="https://colab.research.google.com/github/thisisanmolkumar/DL_Lab/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing libraries

In [ ]:
import numpy as np
import torch

### Creating 1D, 2D, and 3D tensors using PyTorch and NumPy

In [ ]:
numpy_1d_array = np.array([1, 2, 3, 4, 5])
numpy_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
numpy_3d_array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

torch_1d_tensor = torch.tensor([1, 2, 3, 4, 5])
torch_2d_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch_3d_tensor = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

print("NumPy 1D Array:\n", numpy_1d_array)
print("NumPy 2D Array:\n", numpy_2d_array)
print("NumPy 3D Array:\n", numpy_3d_array)
print("\nPyTorch 1D Tensor:\n", torch_1d_tensor)
print("PyTorch 2D Tensor:\n", torch_2d_tensor)
print("PyTorch 3D Tensor:\n", torch_3d_tensor)

NumPy 1D Array:
 [1 2 3 4 5]
NumPy 2D Array:
 [[1 2 3]
 [4 5 6]]
NumPy 3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

PyTorch 1D Tensor:
 tensor([1, 2, 3, 4, 5])
PyTorch 2D Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
PyTorch 3D Tensor:
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


### Addition, subtraction, multiplication, and division

In [ ]:
numpy_array_a = np.array([10, 20, 30, 40, 50])
numpy_array_b = np.array([1, 2, 3, 4, 5])

torch_tensor_a = torch.tensor([10, 20, 30, 40, 50])
torch_tensor_b = torch.tensor([1, 2, 3, 4, 5])

print("NumPy Addition (A + B):", numpy_array_a + numpy_array_b)
print("NumPy Subtraction (A - B):", numpy_array_a - numpy_array_b)
print("NumPy Multiplication (A * B):", numpy_array_a * numpy_array_b)
print("NumPy Division (A / B):", numpy_array_a / numpy_array_b)

print("PyTorch Addition (A + B):", torch_tensor_a + torch_tensor_b)
print("PyTorch Subtraction (A - B):", torch_tensor_a - torch_tensor_b)
print("PyTorch Multiplication (A * B):", torch_tensor_a * torch_tensor_b)
print("PyTorch Division (A / B):", torch_tensor_a / torch_tensor_b)

NumPy Addition (A + B): [11 22 33 44 55]
NumPy Subtraction (A - B): [ 9 18 27 36 45]
NumPy Multiplication (A * B): [ 10  40  90 160 250]
NumPy Division (A / B): [10. 10. 10. 10. 10.]
PyTorch Addition (A + B): tensor([11, 22, 33, 44, 55])
PyTorch Subtraction (A - B): tensor([ 9, 18, 27, 36, 45])
PyTorch Multiplication (A * B): tensor([ 10,  40,  90, 160, 250])
PyTorch Division (A / B): tensor([10., 10., 10., 10., 10.])


### Dot product and matrix multiplication

In [ ]:
numpy_matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
numpy_matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

numpy_dot_product = np.dot(numpy_matrix_a, numpy_matrix_b)
print("NumPy Dot Product (np.dot()):\n", numpy_dot_product)

numpy_matrix_mul_matmul = np.matmul(numpy_matrix_a, numpy_matrix_b)
print("NumPy Matrix Multiplication (np.matmul()):\n", numpy_matrix_mul_matmul)

NumPy Dot Product (np.dot()):
 [[ 58  64]
 [139 154]]
NumPy Matrix Multiplication (np.matmul()):
 [[ 58  64]
 [139 154]]


### Indexing and Slicing

In [ ]:
print("NumPy 1D Array (first element):", numpy_1d_array[0])
print("NumPy 1D Array (third element):", numpy_1d_array[2])

print("PyTorch 1D Tensor (first element):", torch_1d_tensor[0])
print("PyTorch 1D Tensor (third element):", torch_1d_tensor[2])

NumPy 1D Array (first element): 1
NumPy 1D Array (third element): 3
PyTorch 1D Tensor (first element): tensor(1)
PyTorch 1D Tensor (third element): tensor(3)


In [ ]:
print("NumPy 1D Array (first three elements):", numpy_1d_array[0:3])
print("NumPy 1D Array (elements from index 2 to end):", numpy_1d_array[2:])

print("PyTorch 1D Tensor (first three elements):", torch_1d_tensor[0:3])
print("PyTorch 1D Tensor (elements from index 2 to end):", torch_1d_tensor[2:])

NumPy 1D Array (first three elements): [1 2 3]
NumPy 1D Array (elements from index 2 to end): [3 4 5]
PyTorch 1D Tensor (first three elements): tensor([1, 2, 3])
PyTorch 1D Tensor (elements from index 2 to end): tensor([3, 4, 5])


### Using .view(), .reshape(), .unsqueeze(), and .squeeze()

In [ ]:
numpy_array_original = np.arange(1, 10)
numpy_array_original.view()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
numpy_reshaped = numpy_array_original.reshape(3, 3)
print("NumPy Reshaped (3x3):\n", numpy_reshaped)

NumPy Reshaped (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
numpy_2d_array_unsqueeze = np.array([[1, 2, 3], [4, 5, 6]])
torch_2d_tensor_unsqueeze = torch.tensor([[1, 2, 3], [4, 5, 6]])

print("Original NumPy 2D Array:\n", numpy_2d_array_unsqueeze, "\nShape:", numpy_2d_array_unsqueeze.shape)
print("\nOriginal PyTorch 2D Tensor:\n", torch_2d_tensor_unsqueeze, "\nShape:", torch_2d_tensor_unsqueeze.shape)

Original NumPy 2D Array:
 [[1 2 3]
 [4 5 6]] 
Shape: (2, 3)

Original PyTorch 2D Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
Shape: torch.Size([2, 3])


In [ ]:
numpy_expanded_0 = np.expand_dims(numpy_2d_array_unsqueeze, axis=0)
numpy_expanded_1 = np.expand_dims(numpy_2d_array_unsqueeze, axis=1)
numpy_expanded_2 = np.expand_dims(numpy_2d_array_unsqueeze, axis=2)
print("NumPy Expanded (axis=0, shape 1x2x3):\n", numpy_expanded_0, "\nShape:", numpy_expanded_0.shape)
print("NumPy Expanded (axis=1, shape 2x1x3):\n", numpy_expanded_1, "\nShape:", numpy_expanded_1.shape)
print("NumPy Expanded (axis=2, shape 2x3x1):\n", numpy_expanded_2, "\nShape:", numpy_expanded_2.shape)

torch_unsqueezed_0 = torch_2d_tensor_unsqueeze.unsqueeze(0)
torch_unsqueezed_1 = torch_2d_tensor_unsqueeze.unsqueeze(1)
torch_unsqueezed_2 = torch_2d_tensor_unsqueeze.unsqueeze(2)
print("\nPyTorch Unsqueezed (dim=0, shape 1x2x3):\n", torch_unsqueezed_0, "\nShape:", torch_unsqueezed_0.shape)
print("PyTorch Unsqueezed (dim=1, shape 2x1x3):\n", torch_unsqueezed_1, "\nShape:", torch_unsqueezed_1.shape)
print("PyTorch Unsqueezed (dim=2, shape 2x3x1):\n", torch_unsqueezed_2, "\nShape:", torch_unsqueezed_2.shape)

NumPy Expanded (axis=0, shape 1x2x3):
 [[[1 2 3]
  [4 5 6]]] 
Shape: (1, 2, 3)
NumPy Expanded (axis=1, shape 2x1x3):
 [[[1 2 3]]

 [[4 5 6]]] 
Shape: (2, 1, 3)
NumPy Expanded (axis=2, shape 2x3x1):
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]] 
Shape: (2, 3, 1)

PyTorch Unsqueezed (dim=0, shape 1x2x3):
 tensor([[[1, 2, 3],
         [4, 5, 6]]]) 
Shape: torch.Size([1, 2, 3])
PyTorch Unsqueezed (dim=1, shape 2x1x3):
 tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) 
Shape: torch.Size([2, 1, 3])
PyTorch Unsqueezed (dim=2, shape 2x3x1):
 tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]]) 
Shape: torch.Size([2, 3, 1])


In [ ]:
numpy_squeezed = np.squeeze(numpy_expanded_0)
print("NumPy Squeezed (from 1x2x3 to 2x3):\n", numpy_squeezed, "\nShape:", numpy_squeezed.shape)

torch_squeezed = torch_unsqueezed_0.squeeze()
print("\nPyTorch Squeezed (from 1x2x3 to 2x3):\n", torch_squeezed, "\nShape:", torch_squeezed.shape)

torch_squeezed_1_dim = torch_unsqueezed_1.squeeze(1)
print("\nPyTorch Unsqueezed (dim=1) Squeezed at dim=1 (from 2x1x3 to 2x3):\n", torch_squeezed_1_dim, "\nShape:", torch_squeezed_1_dim.shape)

torch_squeezed_2_dim = torch_unsqueezed_2.squeeze(2)
print("\nPyTorch Unsqueezed (dim=2) Squeezed at dim=2 (from 2x3x1 to 2x3):\n", torch_squeezed_2_dim, "\nShape:", torch_squeezed_2_dim.shape)

NumPy Squeezed (from 1x2x3 to 2x3):
 [[1 2 3]
 [4 5 6]] 
Shape: (2, 3)

PyTorch Squeezed (from 1x2x3 to 2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
Shape: torch.Size([2, 3])

PyTorch Unsqueezed (dim=1) Squeezed at dim=1 (from 2x1x3 to 2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
Shape: torch.Size([2, 3])

PyTorch Unsqueezed (dim=2) Squeezed at dim=2 (from 2x3x1 to 2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]]) 
Shape: torch.Size([2, 3])


### Broadcasting

In [ ]:
numpy_array_2d_broadcast = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
numpy_array_1d_broadcast = np.array([10, 20, 30])

torch_tensor_2d_broadcast = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
torch_tensor_1d_broadcast = torch.tensor([10, 20, 30])

print("NumPy 2D Array for broadcasting:\n", numpy_array_2d_broadcast, "\nShape:", numpy_array_2d_broadcast.shape)
print("NumPy 1D Array for broadcasting:\n", numpy_array_1d_broadcast, "\nShape:", numpy_array_1d_broadcast.shape)

print("\nPyTorch 2D Tensor for broadcasting:\n", torch_tensor_2d_broadcast, "\nShape:", torch_tensor_2d_broadcast.shape)
print("PyTorch 1D Tensor for broadcasting:\n", torch_tensor_1d_broadcast, "\nShape:", torch_tensor_1d_broadcast.shape)

NumPy 2D Array for broadcasting:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
Shape: (3, 3)
NumPy 1D Array for broadcasting:
 [10 20 30] 
Shape: (3,)

PyTorch 2D Tensor for broadcasting:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 
Shape: torch.Size([3, 3])
PyTorch 1D Tensor for broadcasting:
 tensor([10, 20, 30]) 
Shape: torch.Size([3])


In [ ]:
numpy_broadcast_result = numpy_array_2d_broadcast + numpy_array_1d_broadcast
print("NumPy 2D Array:\n", numpy_array_2d_broadcast, "\nShape:", numpy_array_2d_broadcast.shape)
print("NumPy 1D Array:\n", numpy_array_1d_broadcast, "\nShape:", numpy_array_1d_broadcast.shape)
print("NumPy Broadcasted Result (2D + 1D):\n", numpy_broadcast_result, "\nShape:", numpy_broadcast_result.shape)

torch_broadcast_result = torch_tensor_2d_broadcast + torch_tensor_1d_broadcast
print("\nPyTorch 2D Tensor:\n", torch_tensor_2d_broadcast, "\nShape:", torch_tensor_2d_broadcast.shape)
print("PyTorch 1D Tensor:\n", torch_tensor_1d_broadcast, "\nShape:", torch_tensor_1d_broadcast.shape)
print("PyTorch Broadcasted Result (2D + 1D):\n", torch_broadcast_result, "\nShape:", torch_broadcast_result.shape)

NumPy 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
Shape: (3, 3)
NumPy 1D Array:
 [10 20 30] 
Shape: (3,)
NumPy Broadcasted Result (2D + 1D):
 [[11 22 33]
 [14 25 36]
 [17 28 39]] 
Shape: (3, 3)

PyTorch 2D Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 
Shape: torch.Size([3, 3])
PyTorch 1D Tensor:
 tensor([10, 20, 30]) 
Shape: torch.Size([3])
PyTorch Broadcasted Result (2D + 1D):
 tensor([[11, 22, 33],
        [14, 25, 36],
        [17, 28, 39]]) 
Shape: torch.Size([3, 3])


### Out-of-place operations

In [ ]:
numpy_original = np.array([1, 2, 3])
torch_original = torch.tensor([1, 2, 3])

print("Original NumPy Array:", numpy_original, "\nID:", id(numpy_original))
print("Original PyTorch Tensor:", torch_original, "\nID:", id(torch_original.data))


Original NumPy Array: [1 2 3] 
ID: 137475673901648
Original PyTorch Tensor: tensor([1, 2, 3]) 
ID: 137475673959600


In [ ]:
numpy_out_of_place = numpy_original + 5
print("NumPy Original Array (after out-of-place):\n", numpy_original, "\nID:", id(numpy_original))
print("NumPy Out-of-Place Result:\n", numpy_out_of_place, "\nID:", id(numpy_out_of_place))

torch_out_of_place = torch_original + 5
print("\nPyTorch Original Tensor (after out-of-place):\n", torch_original, "\nID:", id(torch_original.data))
print("PyTorch Out-of-Place Result:\n", torch_out_of_place, "\nID:", id(torch_out_of_place.data))

NumPy Original Array (after out-of-place):
 [1 2 3] 
ID: 137475673901648
NumPy Out-of-Place Result:
 [6 7 8] 
ID: 137475673903664

PyTorch Original Tensor (after out-of-place):
 tensor([1, 2, 3]) 
ID: 137475673959280
PyTorch Out-of-Place Result:
 tensor([6, 7, 8]) 
ID: 137475673957280


### In-Place Operations


In [ ]:
numpy_original += 10
print("NumPy Array (after in-place operation):\n", numpy_original, "\nID:", id(numpy_original))

torch_original.add_(10)
print("\nPyTorch Tensor (after in-place operation):\n", torch_original, "\nID:", id(torch_original.data))

NumPy Array (after in-place operation):
 [11 12 13] 
ID: 137475673901648

PyTorch Tensor (after in-place operation):
 tensor([11, 12, 13]) 
ID: 137475673960960
